// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go-ecom-admin/internal/product/model"

	mock "github.com/stretchr/testify/mock"
)

// MockCartRepository is an autogenerated mock type for the CartRepository type
type MockCartRepository struct {
	mock.Mock
}

type MockCartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCartRepository) EXPECT() *MockCartRepository_Expecter {
	return &MockCartRepository_Expecter{mock: &_m.Mock}
}

// AddItem provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *MockCartRepository) AddItem(ctx context.Context, userID uint64, productID uint64, quantity int32) error {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, int32) error); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_AddItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItem'
type MockCartRepository_AddItem_Call struct {
	*mock.Call
}

// AddItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - productID uint64
//   - quantity int32
func (_e *MockCartRepository_Expecter) AddItem(ctx interface{}, userID interface{}, productID interface{}, quantity interface{}) *MockCartRepository_AddItem_Call {
	return &MockCartRepository_AddItem_Call{Call: _e.mock.On("AddItem", ctx, userID, productID, quantity)}
}

func (_c *MockCartRepository_AddItem_Call) Run(run func(ctx context.Context, userID uint64, productID uint64, quantity int32)) *MockCartRepository_AddItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(int32))
	})
	return _c
}

func (_c *MockCartRepository_AddItem_Call) Return(_a0 error) *MockCartRepository_AddItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_AddItem_Call) RunAndReturn(run func(context.Context, uint64, uint64, int32) error) *MockCartRepository_AddItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function with given fields: ctx, userID, productID
func (_m *MockCartRepository) GetItem(ctx context.Context, userID uint64, productID uint64) (*model.CartItem, error) {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *model.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*model.CartItem, error)); ok {
		return rf(ctx, userID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) *model.CartItem); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, userID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartRepository_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockCartRepository_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - productID uint64
func (_e *MockCartRepository_Expecter) GetItem(ctx interface{}, userID interface{}, productID interface{}) *MockCartRepository_GetItem_Call {
	return &MockCartRepository_GetItem_Call{Call: _e.mock.On("GetItem", ctx, userID, productID)}
}

func (_c *MockCartRepository_GetItem_Call) Run(run func(ctx context.Context, userID uint64, productID uint64)) *MockCartRepository_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *MockCartRepository_GetItem_Call) Return(_a0 *model.CartItem, _a1 error) *MockCartRepository_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartRepository_GetItem_Call) RunAndReturn(run func(context.Context, uint64, uint64) (*model.CartItem, error)) *MockCartRepository_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockCartRepository) ListByUser(ctx context.Context, userID uint64) ([]*model.CartEntry, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []*model.CartEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*model.CartEntry, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*model.CartEntry); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.CartEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCartRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockCartRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockCartRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockCartRepository_ListByUser_Call {
	return &MockCartRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockCartRepository_ListByUser_Call) Run(run func(ctx context.Context, userID uint64)) *MockCartRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockCartRepository_ListByUser_Call) Return(_a0 []*model.CartEntry, _a1 error) *MockCartRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCartRepository_ListByUser_Call) RunAndReturn(run func(context.Context, uint64) ([]*model.CartEntry, error)) *MockCartRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveItems provides a mock function with given fields: ctx, userID, productIDs
func (_m *MockCartRepository) RemoveItems(ctx context.Context, userID uint64, productIDs []uint64) error {
	ret := _m.Called(ctx, userID, productIDs)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []uint64) error); ok {
		r0 = rf(ctx, userID, productIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_RemoveItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveItems'
type MockCartRepository_RemoveItems_Call struct {
	*mock.Call
}

// RemoveItems is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - productIDs []uint64
func (_e *MockCartRepository_Expecter) RemoveItems(ctx interface{}, userID interface{}, productIDs interface{}) *MockCartRepository_RemoveItems_Call {
	return &MockCartRepository_RemoveItems_Call{Call: _e.mock.On("RemoveItems", ctx, userID, productIDs)}
}

func (_c *MockCartRepository_RemoveItems_Call) Run(run func(ctx context.Context, userID uint64, productIDs []uint64)) *MockCartRepository_RemoveItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].([]uint64))
	})
	return _c
}

func (_c *MockCartRepository_RemoveItems_Call) Return(_a0 error) *MockCartRepository_RemoveItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_RemoveItems_Call) RunAndReturn(run func(context.Context, uint64, []uint64) error) *MockCartRepository_RemoveItems_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuantity provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *MockCartRepository) UpdateQuantity(ctx context.Context, userID uint64, productID uint64, quantity int32) error {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuantity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, int32) error); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCartRepository_UpdateQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuantity'
type MockCartRepository_UpdateQuantity_Call struct {
	*mock.Call
}

// UpdateQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - productID uint64
//   - quantity int32
func (_e *MockCartRepository_Expecter) UpdateQuantity(ctx interface{}, userID interface{}, productID interface{}, quantity interface{}) *MockCartRepository_UpdateQuantity_Call {
	return &MockCartRepository_UpdateQuantity_Call{Call: _e.mock.On("UpdateQuantity", ctx, userID, productID, quantity)}
}

func (_c *MockCartRepository_UpdateQuantity_Call) Run(run func(ctx context.Context, userID uint64, productID uint64, quantity int32)) *MockCartRepository_UpdateQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64), args[3].(int32))
	})
	return _c
}

func (_c *MockCartRepository_UpdateQuantity_Call) Return(_a0 error) *MockCartRepository_UpdateQuantity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCartRepository_UpdateQuantity_Call) RunAndReturn(run func(context.Context, uint64, uint64, int32) error) *MockCartRepository_UpdateQuantity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCartRepository creates a new instance of MockCartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCartRepository {
	mock := &MockCartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
